# url: https://y7kim.github.io
# baseurl: "https://americanbuilderhardwoodfloor.com/"

# Site settings
title: American Builder Hardwood Floor 
email: americanbuilderhardwood@gmail.com
description: "Expert hardwood floor refinishing, installation, and repair services to enhance and restore your home's elegance."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: facebook
  #   url: https://www.facebook.com/andynguyen1978
  - title: google
    url: https://maps.app.goo.gl/JXvJqGBh7SBh4Kyy6

# Postal address (add as many lines as necessary)
address:
  - line: 11 Forest Ave
  - line: Quincy, MA 02169

# Build settings
markdown: kramdown
permalink: pretty

image_fulls_loc: "/img/various/full"
image_thumbs_loc: "/img/various/thumb"